### PR TITLE
[ppc64le]: Updated job config for release-1.15 for ppc64le

### PR DESCRIPTION
**Pull request by valen-mascarenhas14**
Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)

**Which issue(s) this PR fixes**:<br>

This PR updates the ppc64le specific job config for release 1.15 for operator, client, serving, eventing and eventing-reconciler and fixes the chainguard image issue for ppc64le.

### CODE REVIEW

**Comment by valen-mascarenhas14** [comment]
@upodroid @dprotaso can you please approve this PR?

**Comment by valen-mascarenhas14** [comment]
@upodroid Could you please merge this PR if everything's fine ?

**Review by upodroid — APPROVED** [review]

**Comment by dsimansk** [comment]
I don't think new jobs are necessary. The issue seems to be `ko` and base image combination, per Serving PR. https://github.com/knative/serving/pull/15407

That was cherry-picked to release-1.15 branch, but release job failed on e2e tests. I've triggered a new run.

**Comment by dsimansk** [comment]
Once Serving release-1.15 jobs passed, the images are published in both s390x and ppc64 archs.

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 918,
         "digest": "sha256:bb746b99bbcc86154c4fea433a324f2f92612a99ea9e8a14265a22755282834e",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 918,
         "digest": "sha256:6f1368aa67ba0aa1b4f0977e2612a5194dc3d5cb66b097dbb16a0bf52c188f2f",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 918,
         "digest": "sha256:6506b39b93e5848f834f9ab63a920c94e09944b4c090d21bbfebce0df5457f0b",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 918,
         "digest": "sha256:eb3fc7e589ee635d42aa260742a53d971f6aac2eb557d5b16e11edf229ce5e07",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 918,
         "digest": "sha256:322c763c780c89becada954ae89c7ab5cc932b9c0ef8d2a01d06430bbec62b4d",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ],
   "annotations": {
      "org.opencontainers.image.base.digest": "sha256:2dd40d6660115085ef09597f8951c4366dddb6f5351f0e4972b824e9e61abfb1",
      "org.opencontainers.image.base.name": "ghcr.io/wolfi-dev/static:alpine"
   }
}
```

**Comment by dprotaso** [comment]
no the base image was changed to have s390x/ppc support - so we don't need this PR

**Pull request closed without merging**
