### PR TITLE
HoldTillRename: Rename knative-sandbox to knative-extensions

### PR DESCRIPTION
**Pull request by davidhadas**
This is an auotmated PR to replace  strings to . Do not merge until Rename knative-sandbox org is renamed to knative-extensions

### CODE REVIEW

**Comment by davidhadas** [comment]
@upodroid

**Review by upodroid — APPROVED** [review]

**Comment by upodroid** [comment]
/override "unit-tests_infra_main"
/override "build-tests_infra_main"
/override "verify / Verify Deps and Codegen"

**Pull request merged**
