### PR TITLE
Added the repo autoscaler-keda

### PR DESCRIPTION
**Pull request by skonto**
**Which issue(s) this PR fixes**:<br>
Fixes
- Needed by https://github.com/knative/community/issues/1527
-  Similar to https://github.com/knative/infra/pull/211/

### CODE REVIEW

**Comment by skonto** [comment]
Repo is still empty but I am working on the actual repo content so tests will be run against the forthcoming PR after this is merged I suspect.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Review by upodroid — APPROVED** [review]

**Pull request merged**
