### PR TITLE
Build release-jobs-syncer as part of the image

### PR DESCRIPTION
**Pull request by upodroid**
/cc @kvmware 

The `release-jobs-syncer` job is misconfigured right now and checks out the old repo. The tool needs to be compiled and called with the new repository.

https://github.com/knative/test-infra/pull/3840 needs to run in this repo which means the extra_refs have to be knative/infra and the job needs to look like this:

```yaml
- cron: "0 */2 * * *" # Every other hour
  name: ci-knative-prow-jobs-syncer
  agent: kubernetes
  decorate: true
  cluster: prow-build
  extra_refs:
  - org: knative
    repo: infra
    base_ref: main
    path_alias: knative.dev/infra
  annotations:
    testgrid-dashboards: utilities
    testgrid-tab-name: ci-knative-prow-jobs-syncer
  reporter_config:
    slack:
      channel: knative-productivity
      job_states_to_report:
        - failure
      report_template: '"The prow-jobs-syncer periodic job has failed, please check the logs: <{{.Status.URL}}|View logs>"'
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/prow-tests:v20230524-3500eda5
      imagePullPolicy: Always
      command:
      - "runner.sh"
      args:
      - bash
      - -c
      - |
        release-jobs-syncer --github-account=/etc/prow-auto-bumper-github-token/token \
          --git-userid=knative-prow-updater-robot \
          --git-username='Knative Prow Updater Robot' \
          --git-email=knative-prow-updater-robot@google.com \
          --prow-job-config-root-path=prow/jobs_config \
          --regen-config-script=hack/generate-configs.sh \
          --label=skip-review
      volumeMounts:
      - name: github-credentials
        mountPath: /etc/prow-auto-bumper-github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github-credentials
      secret:
        secretName: github-credentials
        items:
        - key: auto_bumper_token
          path: token
    - name: ssh
      secret:
        secretName: github-credentials
        defaultMode: 0700
        items:
        - key: id_rsa
          path: id_rsa
        - key: id_rsa_pub
          path: id_rsa.pub
        - key: known_hosts
          path: known_hosts

```

### CODE REVIEW

**Comment by kvmware** [comment]
looks like one failing test

**Comment by upodroid** [comment]
go mod is broken I'll need to investigate

**Comment by upodroid** [comment]
this is fixed now, tested it by building the image

**Pull request merged**
