### PR TITLE
docker_config env variable added for ppc64le jobs

### PR DESCRIPTION
**Pull request by valen-mascarenhas14**
Signed-off-by: Valen Mascarenhas [Valen.Mascarenhas@ibm.com](mailto:Valen.Mascarenhas@ibm.com)

Which issue(s) this PR fixes:

Fixes:
docker config env variable for ppc64le jobs

### CODE REVIEW

**Comment by valen-mascarenhas14** [comment]
@evankanderson @krsna-m if everything is fine , could you please merge this PR ?

**Review by evankanderson — APPROVED** [review]
/lgtm
/approve

**Comment by evankanderson** [comment]
Prow will merge this PR when it's approved, I expect.  I don't think we have humans with merge rights at the moment in any practical sense.

**Comment by evankanderson** [comment]
This appears to only set env vars, and not to expose any new data to the runner, so I'm assessing this as "safe", but @krsna-m might tell me I was wrong.

**Comment by valen-mascarenhas14** [comment]
@pierDipi can u please merge this PR ?

**Comment by pierDipi** [comment]
I think I'm not an approver

/approve

**Comment by pierDipi** [comment]
cc @knative/productivity-leads

**Pull request merged**
